### ISSUE TITLE
milan on pypi

### ISSUE THREAD

**Issue by fscherf** [luminous198/test#1]
Hi @luminous198,

Is this repository linked to `https://pypi.org/project/milan/`? Because its description states it is for testing. If so, please contact me, because I have some questions about it.

email: mail@florianscherf.de

**Comment by fscherf** [comment]
I really like this name, and would like to use it for this project: https://github.com/fscherf/milan
Since this looks abandoned, I’ve gone ahead and filed a PEP 541 request (https://github.com/pypi/support/issues/3375), would you be willing to let me have the name?

**Comment by luminous198** [comment]
Hi FlorianOf course, this was just a test project by me for checking how pypi works, please go ahead if you want the name.Let me know in case I need to do something for the same.RegardsMilan Sent from my iPhoneOn 9 Apr 2024, at 02:31, Florian Scherf ***@***.***> wrote:﻿
I really like this name, and would like to use it for this project: https://github.com/fscherf/milan
Since this looks abandoned, I’ve gone ahead and filed a PEP 541 request (pypi/support#3375), would you be willing to let me have the name?

**Comment by fscherf** [comment]
Hi @luminous198!
Great! Thanks in advance! :) 
The fastest and easiest would be if you just transfer ownership of the pypi project to my pypi account (https://pypi.org/user/fscherf/). Or you add me, and I remove you from the project afterward.

**Comment by fscherf** [comment]
FTR: @luminous198 added me as owner. Thanks a lot!
